##
## Default (built-in) settings
##

hosts:
  github:
    name: GitHub
#    adapter: oktokit

defaults:
  hosts:
    auth: ssh
  repos:
    host: github

##
## System level configuration
## $(dirname "${BASH_SOURCE[0]}")/.pitchfork.yml
##
## User level configuration
## $HOME/.pitchfork.yml
##
## Project level configuration
## $PWD/(../).pitchfork.yml
##
## Local overrides at any level
## (add to gitignore: .pitchfork.*.yml)
## .pitchfork.local.yml
##
## Extensible style
## .pitchfork.00-first.yml
## .pitchfork.99-last.yaml
##
## Via environment variables
## PF_HOSTS_GITHUB_USER=octocat pitchfork inspect
## PITCHFORK_HOSTS_GITHUB_USER=$PF_HOSTS_GITHUB_USER pitchfork inspect
##
## Using command-line arguments
## pitchfork inspect --hosts-github-user=$PITCHFORK_HOSTS_GITHUB_USER
##

##
## Example of expected project-specific config file:
##
# repos:
## Direct clone version
#   rails-dev-box:
#     path: ~/work/rails-dev-box
#     owner: rails
## Forked version
#   rails:
#     path: ~/work/rails-dev-box/rails
#     upstream: rails

##
## Example of possible GitHub Enterprise host configuration:
##
# hosts:
#   your_gh_ent:
#     name: Your GitHub Enterprise
## api_endpoint = "https://#{host.api_endpoint}/api/v3/"
#     api_endpoint: github.example.com
#     auth: https
#
# defaults:
#   repos:
#     host: your_gh_ent
## path ||= "#{base_dir}/#{repo_name}"
#     base_dir: ~/work
#     upstream: your_default_org
